### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by mschwaig** [serokell/update-daemon#7]
This project looks great!

I have implemented something very similar for GitLab in Python.
You can find my project `flake-auto-update-for-gitlab` here:
https://gitlab.com/mschwaig/flake-auto-update-for-gitlab

`flake-auto-update-for-gitlab` is in active use on a private GitLab instance as an auxiliary part of a research project, but is in much rougher shape than this form the looks of it. If GitLab support works out nicely here I hope I could retire my project.

Let me know if you already have ideas for adding GitLab support or suggestions about what kind of help would be useful.

**Comment by balsoft** [comment]
Hey! There is preliminary gitlab support now. It would be great if you could check it out!

**Comment by balsoft** [comment]
Also see #9
